#Поскольку задание для локальной машины, целевая система Ubuntu 20.04
#Запускаем MySQL
- hosts: temp
  gather_facts: true
  tasks:
    - name: Run mysql
      systemd:
        state: started
        name: mysql-server


