#Работаем с Ubuntu 20.04
---
- hosts: test
  gather_facts: false
  tasks:
  
    - name: Install webserver with custom root
      include_role:
        name: task_b692
      tags: 
      - install_nginx
      - change_root

#Хотя конечно можно было обойтись и статическим вызовом роли вместо динамического с двумя тагами. но так правильнее.

